version: "3.8"
services:
  db:
    image: postgres:15
    container_name: karaoke_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: karaoke
      POSTGRES_USER: karaoke
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - .volume/postgresql:/var/lib/postgresql/data
